### ISSUE TITLE
prepare data

### ISSUE THREAD

**Issue by zhangxue123** [UCSD-AI4H/PathVQA#2]
I notice VQA_Dataset have many unknown files:    train_q_dict.p,   train_a_dict.p,  vqa_train_final_3000.json,   trainval.zarr,   trainval_boxes.zarr,   trainval_image_size.csv,  vqa_test_toked.json,  glove.6B.  d.txt

I want to konow how to prepare these documents, thanks!

**Comment by jkooy** [comment]
Our PathVQA dataset is in the Google drive. It has already been splited for you. Why you are using the VQA dataset? We don't provide  the document for VQA dataset, these can be found on Stanford VQA website.
