### ISSUE TITLE
evaluation_script erro

### ISSUE THREAD

**Issue by zhangxue123** [UCSD-AI4H/PathVQA#3]
I think your evaluation script has a question.
PathVQA/Evaluation script/evaluation_script.py

line 32

def calculate_bleu(weights, pn, n, bp):
    sum_wlogp = 0
    for i in range(n):
        **if pn[i] != 0:**
            sum_wlogp += float(weights[i]) * math.log(pn[i])
    bleu_result = bp * math.exp(sum_wlogp)
    return bleu_result

may be should write to this:

def calculate_bleu(weights, pn, n, bp):
    sum_wlogp = 0
    for i in range(n):
        **if pn[i] == 0: pn[i] = sys.float_info.min
        sum_wlogp += float(weights[i]) * math.log(pn[i])**
    bleu_result = bp * math.exp(sum_wlogp)
    return bleu_result

**Comment by jkooy** [comment]
We evaluate the score when the modified precision is not zero. It's meaningless to calculate the zero stuation. You can add the try.. except statements for except case. This program is basically the source code of NLTK package, or maybe you can directly install the NLTK package and call their function.
