### ISSUE TITLE
How to creat 2200 highest frequencies?

### ISSUE THREAD

**Issue by 15122901359** [UCSD-AI4H/PathVQA#4]
I would like to ask how do you prepare the high-frequency vocabulary? Here's my code for generating high-frequency words. Did you prepare it that way？
`def ans_stat(stat_ans_list):
    ans_to_ix = {}
    ix_to_ans = {}
    ans_freq_dict = {}

    for ans in stat_ans_list:
        ans_proc = prep_ans(ans['multiple_choice_answer'])
        if ans_proc not in ans_freq_dict:
            ans_freq_dict[ans_proc] = 1
        else:
            ans_freq_dict[ans_proc] += 1

    ans_freq_filter = ans_freq_dict.copy()
    for ans in ans_freq_dict:
        if ans_freq_dict[ans] <= 0:
            ans_freq_filter.pop(ans)

    for ans in ans_freq_filter:
        ix_to_ans[ans_to_ix.__len__()] = ans
        ans_to_ix[ans] = ans_to_ix.__len__()

    return ans_to_ix, ix_to_ans`

**Comment by jkooy** [comment]
No trick is here. Just count like yours and sort then.
